### ISSUE TITLE
Wrong export of description field

### ISSUE THREAD

**Issue by pvaessen** [kffein/Craft-export-Csv#10]
When I do a export of a description field of type Redactor the csv cell fields contain ascii characters and broken html tags.
Example: 
In the CMS I have this for the description field:
<p>Are you ready for CPQ? If you’re a manufacturer of configured products, and the CPQ system you use in your selling process can’t handle the complexity of your offerings, it’s time to consider a step up to Infor’s advanced CPQ solution software. With Infor CPQ you get the tools you need to increase sales, reduce costs, and differentiate your brand.</p>
After export the field looks like this:
"<p>Are   you ready for CPQ? If you\u2019re a manufacturer of configured products, and   the CPQ system you use in your selling process can\u2019t handle the   complexity of your offerings, it\u2019s time to consider a step up to   Infor\u2019s advanced CPQ solution software. With Infor CPQ you get the tools   you need to increase sales, reduce costs, and differentiate your   brand.<\/p>"
--

Is there a solution for this issue ?

**Comment by kffein-david** [comment]
As the quote is used to separate each CSV column, we don't have the choice to addSlash on field content.

We are working on a version of the plugin that will allow to export in xls file and get ride of the separator character.
