### ISSUE TITLE
Ability to run as cron job

### ISSUE THREAD

**Issue by dmatthams** [kffein/Craft-export-Csv#12]
Would be great to have a public url to start a job (like feed me) so a cron job can be setup to keep the CSV up to date.

**Comment by jlachancekffein** [comment]
Indeed, this can cause a problem if the control panel is not active when exporting the file.

However, queue management is not the responsibility of this plugin.

I suggest you to install the AsyncQueue plugin to properly manage the queue even if the control panel is not active.

https://plugins.craftcms.com/async-queue
