### ISSUE TITLE
Dos it just export entries, or can I choose other tables of data? 

### ISSUE THREAD

**Issue by amityweb** [kffein/Craft-export-Csv#13]
Dos it just export entries, or can I choose other tables of data? 

For example, we use Contact Form Extensions which saves contact form enquiries into it own tables, and we would like to export it. 

Thanks

**Comment by bertheyman** [comment]
@amityweb Did you get to test it for contact form extensions?

**Comment by amityweb** [comment]
We have not exported the data no, due to not getting any response here.

**Comment by bertheyman** [comment]
Okay, thanks for letting me know!

Update: for anyone wondering: the plugins can only export regular entries.

**Comment by CodeCurosity** [comment]
does it export the assets and custom fields?

**Comment by jlachancekffein** [comment]
Sorry for the delay in responding.

The plugin aims to export entries only.

We are currently working on a new version of the plugin that will allow the export of most Craft elements and not just entries.
