### ISSUE TITLE
Fails on export

### ISSUE THREAD

**Issue by danleecreates** [kffein/Craft-export-Csv#16]
@kffein-david  Noticed that the plugin doesn't want to work. It fails when exporting. Retrying the task in the queue manager doesn't allow it to proceed either - it gets stuck on pending.

I noticed the plugin hasn't been updated in some time.

**Comment by danleecreates** [comment]
Bit more information on this: I'm getting the following error: 

`Getting unknown property: craft\elements\Entry::{title}`

**Comment by ed-kffein** [comment]
Hello @nearkingdom 

You should not use brackets to encapsulate your field name if you're not using a combination of fields. 
To fix your problem you have to use `title` instead of `{title}` in your export configuration. 

Thank you
