### ISSUE TITLE
Settings page throws error "Call to a member function getAcceptsJson() on string"

### ISSUE THREAD

**Issue by bcartier** [kffein/Craft-export-Csv#17]
I can't seem to configure this module after an error-free installation. 

**Craft CMS 3.5.7**
PHP 7.3.1
Purchased license (not a trial)

**1. in /vendor/craftcms/cms/src/web/Controller.phpat line 183**
174175176177178179180181182183184185186187188189190191192 
    /**
     * @inheritdoc
     */
    public function runAction($id, $params = [])
    {
        try {
            return parent::runAction($id, $params);
        } catch (\Throwable $e) {
            if ($this->request->getAcceptsJson()) {
                Craft::$app->getErrorHandler()->logException($e);
                if (!YII_DEBUG && !$e instanceof UserException) {
                    $message = Craft::t('app', 'A server error occurred.');
                } else {
                    $message = $e->getMessage();
                }
                if ($e instanceof ClientException) {
                    $statusCode = $e->getCode();
                    if (($response = $e->getResponse()) !== null) {
**2. in vendor/yiisoft/yii2/base/Module.php at line 528**
– craft\web\Controller::runAction('', ['p' => 'admin/craft-export-csv/settings'])
522523524525526527528529530531532533534        $parts = $this->createController($route);
        if (is_array($parts)) {
            /* @var $controller Controller */
            list($controller, $actionID) = $parts;
            $oldController = Yii::$app->controller;
            Yii::$app->controller = $controller;
            $result = $controller->runAction($actionID, $params);
            if ($oldController !== null) {
                Yii::$app->controller = $oldController;
            }
 
            return $result;
        }
**3. in /vendor/craftcms/cms/src/web/Application.php at line 280**
– yii\base\Module::runAction('craft-export-csv/settings', ['p' => 'admin/craft-export-csv/settings'])
274275276277278279280281282283284285286     * @param string $route
     * @param array $params
     * @return Response|null The result of the action, normalized into a Response object
     */
    public function runAction($route, $params = [])
    {
        $result = parent::runAction($route, $params);
 
        if ($result !== null) {
            if ($result instanceof Response) {
                return $result;
            }
 
**4. in /vendor/yiisoft/yii2/web/Application.php at line 103**
– craft\web\Application::runAction('craft-export-csv/settings', ['p' => 'admin/craft-export-csv/settings'])
5. in /Users/brentcartier/Sites2/dentistonline-craft/vendor/craftcms/cms/src/web/Application.php at line 265– yii\web\Application::handleRequest(craft\web\Request)
259260261262263264265266267268269270271        if (($response = $this->_processActionRequest($request)) !== null) {
            return $response;
        }
 
        // If we're still here, finally let Yii do it's thing.
        try {
            return parent::handleRequest($request);
        } catch (\Throwable $e) {
            $this->_unregisterDebugModule();
            throw $e;
        }
    }
 
**6. in /vendor/yiisoft/yii2/base/Application.php at line 386**
– craft\web\Application::handleRequest(craft\web\Request)
7. in /public/index.php at line 21– yii\base\Application::run()
15161718192021    Dotenv\Dotenv::create(CRAFT_BASE_PATH)->load();
}
 
// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();
$_GET = [
    'p' => 'admin/craft-export-csv/settings',
];

**Comment by kffein-david** [comment]
Hi Brent.

We are working on this ( related to craft 3.5).

Next release will fix it.

Thank you

**Comment by jlachancekffein** [comment]
Fix will the latest release.

https://github.com/kffein/Craft-export-Csv/releases/tag/v1.0.9
