### ISSUE TITLE
Error: fopen(uploads/test.csv): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by ademers** [kffein/Craft-export-Csv#2]
When I try to generate the csv file via Report in the Craft CP, I get the following error:

```
PHP Warning – yii\base\ErrorException
fopen(uploads/test.csv): failed to open stream: No such file or directory
```

Seems like the plugin is looking for an `uploads` directory. If so, where does this come from? Was I supposed to create it somewhere? I didn't see anything in the docs.

Thanks!

**Comment by pierreluckffein** [comment]
Thank for your attention on this issue

An update has been released that fix this problem, if the folder that contains generated reports does not exist it will be created.
