### ISSUE TITLE
Setting unknown property: kffein\craftexportcsv\controllers\ReportsController::request

### ISSUE THREAD

**Issue by przzz27** [kffein/Craft-export-Csv#20]
This error appears when trying to look into the plugin settings on craft's cp.
![image](https://user-images.githubusercontent.com/61523021/108575769-2ede0b80-72d0-11eb-89ba-f5e40b413b55.png)

The error says:
Setting unknown property: kffein\craftexportcsv\controllers\ReportsController::request

It appeared after updating the plugin from version
1.0.8 to 1.0.12

Some other details:
Php version: 7.4.15
Craft version:  Craft Pro 3.4.27
Yii version: 2.0.35
Twig version: 2.12.5
![image](https://user-images.githubusercontent.com/61523021/108575917-985e1a00-72d0-11eb-8863-33dd69cd14ae.png)

**Comment by ed-kffein** [comment]
Hi @przzz27 
We published a fix for this problem on release 1.0.13 that will fix your issue on Craft 3.4
Thank you
