### ISSUE TITLE
Matrix field

### ISSUE THREAD

**Issue by redkrupp** [kffein/Craft-export-Csv#22]
Hi,

How do I export the matrix field?

Matrix handle is contentBuilder. Field named "copy".

![KxAd57R](https://user-images.githubusercontent.com/1551388/123695141-04065400-d87c-11eb-971f-931528be7055.png)

Please advise.

**Comment by ed-kffein** [comment]
Hello @EmptyStreets, 

Exporting content from matrix fields is not currently supported by this plugin. 

Best regards, 
Edouard
